apiVersion: v1
kind: Secret 
metadata:
  name: neko-secrets
  namespace: neko
type: Opaque
stringData:
  SESSION_SECRET: "session_secret(64b)"
  TWITTER_CONSUMER_KEY: "twitter_consum_key_from_x_dev_console"
  TWITTER_CONSUMER_SECRET: "twitter_consum_secret_from_x_dev_console"